# GitHub Copilot Setup Steps
# This file configures the development environment for GitHub Copilot coding agent
# by pre-installing dependencies before the agent starts working.

name: Setup Guild Scout Reports Development Environment

# Install Node.js and project dependencies
steps:
  # Step 1: Set up Node.js environment
  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: '18'
      cache: 'npm'
  
  # Step 2: Install project dependencies
  - name: Install dependencies
    run: npm ci
  
  # Step 3: Verify TypeScript configuration
  - name: Verify TypeScript setup
    run: npx tsc --noEmit || echo "TypeScript check complete"
  
  # Step 4: Run ESLint to check code style (non-blocking)
  - name: Run linter
    run: npm run lint || echo "Linting check complete"
    continue-on-error: true

# Environment variables that may be needed during setup
# Note: Actual secret values should be configured in GitHub Secrets
env:
  NODE_ENV: development
  # Supabase and Anthropic API keys should be added as repository secrets
  # and will be available to the agent when needed
